using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ApiCommon.BaseControllers;

// **************************************************
//                                                 //
//  Code generated by Levan Doliashvili "API Generator"  //
//												   //
// **************************************************

namespace OnlineShop.Api.Controllers
{
	[Route("v1/Category")]
	public class CategoryController : BaseApiController
	{	

		[HttpPost("CreateCategory")]
		public async Task<IActionResult> CreateCategory([FromBody] OnlineShop.Domain.Categories.Commands.CreateCategoryCommand command) 
		{
			await Mediator.SendAsync(command);
			return Ok();
		}	

		[HttpPost("DeleteCategory")]
		public async Task<IActionResult> DeleteCategory([FromBody] OnlineShop.Domain.Categories.Commands.DeleteCategoryCommand command) 
		{
			await Mediator.SendAsync(command);
			return Ok();
		}	

		[HttpGet("GetCategories")]
		[ProducesResponseType(typeof(System.Collections.Generic.List<OnlineShop.Domain.Categories.ReadModels.CategoryReadModel>), 200)]
		public async Task<IActionResult> GetCategories([FromQuery] OnlineShop.Domain.Categories.Queries.GetCategories query) 
		{
			var data = await Mediator.QueryAsync(query);
			return Ok(data);
		}
	}
}