ALTER TABLE Images 
DROP CONSTRAINT [FK__Images__ProductI__29572725]; 

ALTER TABLE Images  WITH CHECK ADD  CONSTRAINT [FK__Images__Product] FOREIGN KEY(ProductId)
REFERENCES Products (Id)
ON DELETE CASCADE